# IMPORT LIBRARY

In [2]:
import os 
import pandas as pd 
import matplotlib as plt

# ETL

Extract

In [281]:
Data = pd.DataFrame()
for i in os.listdir(os.getcwd()):
    if i.endswith('.csv'):
        Data = Data.append(pd.read_csv(i))
Data

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
11681,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001"
11682,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016"
11683,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016"
11684,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016"
11685,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016"

Transform

In [282]:
Data.columns

Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')

In [283]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 186850 entries, 0 to 11685
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          186305 non-null  object
 1   Product           186305 non-null  object
 2   Quantity Ordered  186305 non-null  object
 3   Price Each        186305 non-null  object
 4   Order Date        186305 non-null  object
 5   Purchase Address  186305 non-null  object
dtypes: object(6)
memory usage: 10.0+ MB

# DATA CLEANING & DATA MANIPULATION

In [284]:
Data.isna().sum()

Order ID            545
Product             545
Quantity Ordered    545
Price Each          545
Order Date          545
Purchase Address    545
dtype: int64

In [285]:
Data = Data.dropna()
Data

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
11681,259353,AAA Batteries (4-pack),3,2.99,09/17/19 20:56,"840 Highland St, Los Angeles, CA 90001"
11682,259354,iPhone,1,700,09/01/19 16:00,"216 Dogwood St, San Francisco, CA 94016"
11683,259355,iPhone,1,700,09/23/19 07:39,"220 12th St, San Francisco, CA 94016"
11684,259356,34in Ultrawide Monitor,1,379.99,09/19/19 17:30,"511 Forest St, San Francisco, CA 94016"
11685,259357,USB-C Charging Cable,1,11.95,09/30/19 00:18,"250 Meadow St, San Francisco, CA 94016"

In [286]:
Data['Order Date'].head()

0    04/19/19 08:46
2    04/07/19 22:30
3    04/12/19 14:38
4    04/12/19 14:38
5    04/30/19 09:27
Name: Order Date, dtype: object

In [287]:
Data['Order Date'] = pd.to_datetime(Data['Order Date'],format='%m/%d/%y %H:%M',errors = 'coerce')
Data

C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/254897764.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Order Date'] = pd.to_datetime(Data['Order Date'],format='%m/%d/%y %H:%M',errors = 'coerce')

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,"917 1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,"333 8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...
11681,259353,AAA Batteries (4-pack),3,2.99,2019-09-17 20:56:00,"840 Highland St, Los Angeles, CA 90001"
11682,259354,iPhone,1,700,2019-09-01 16:00:00,"216 Dogwood St, San Francisco, CA 94016"
11683,259355,iPhone,1,700,2019-09-23 07:39:00,"220 12th St, San Francisco, CA 94016"
11684,259356,34in Ultrawide Monitor,1,379.99,2019-09-19 17:30:00,"511 Forest St, San Francisco, CA 94016"
11685,259357,USB-C Charging Cable,1,11.95,2019-09-30 00:18:00,"250 Meadow St, San Francisco, CA 94016"

In [288]:
Data['Street Number'] = Data['Purchase Address'].str.split(' ', n=1).str[0]
Data['Address'] = Data['Purchase Address'].str.split(' ', n=1).str[1]
Data.drop('Purchase Address',axis=1 , inplace=True)
Data

C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/1892461468.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Street Number'] = Data['Purchase Address'].str.split(' ', n=1).str[0]
C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/1892461468.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Address'] = Data['Purchase Address'].str.split(' ', n=1).str[1]
C:\Users\MAHMOUD\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Street Number,Address
0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,917,"1st St, Dallas, TX 75001"
2,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,682,"Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,2019-04-12 14:38:00,669,"Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,669,"Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,333,"8th St, Los Angeles, CA 90001"
...,...,...,...,...,...,...,...
11681,259353,AAA Batteries (4-pack),3,2.99,2019-09-17 20:56:00,840,"Highland St, Los Angeles, CA 90001"
11682,259354,iPhone,1,700,2019-09-01 16:00:00,216,"Dogwood St, San Francisco, CA 94016"
11683,259355,iPhone,1,700,2019-09-23 07:39:00,220,"12th St, San Francisco, CA 94016"
11684,259356,34in Ultrawide Monitor,1,379.99,2019-09-19 17:30:00,511,"Forest St, San Francisco, CA 94016"
11685,259357,USB-C Charging Cable,1,11.95,2019-09-30 00:18:00,250,"Meadow St, San Francisco, CA 94016"

In [289]:
split_address = Data['Address'].str.split(',', expand=True)
Data['Street Name'] = split_address[0]
Data['City'] = split_address[1]
Data['State'] = split_address[2]
Data

C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/1305411780.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Street Name'] = split_address[0]
C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/1305411780.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['City'] = split_address[1]
C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/1305411780.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['State'] = split_address[2]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Street Number,Address,Street Name,City,State
0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,917,"1st St, Dallas, TX 75001",1st St,Dallas,TX 75001
2,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,682,"Chestnut St, Boston, MA 02215",Chestnut St,Boston,MA 02215
3,176560,Google Phone,1,600,2019-04-12 14:38:00,669,"Spruce St, Los Angeles, CA 90001",Spruce St,Los Angeles,CA 90001
4,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,669,"Spruce St, Los Angeles, CA 90001",Spruce St,Los Angeles,CA 90001
5,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,333,"8th St, Los Angeles, CA 90001",8th St,Los Angeles,CA 90001
...,...,...,...,...,...,...,...,...,...,...
11681,259353,AAA Batteries (4-pack),3,2.99,2019-09-17 20:56:00,840,"Highland St, Los Angeles, CA 90001",Highland St,Los Angeles,CA 90001
11682,259354,iPhone,1,700,2019-09-01 16:00:00,216,"Dogwood St, San Francisco, CA 94016",Dogwood St,San Francisco,CA 94016
11683,259355,iPhone,1,700,2019-09-23 07:39:00,220,"12th St, San Francisco, CA 94016",12th St,San Francisco,CA 94016
11684,259356,34in Ultrawide Monitor,1,379.99,2019-09-19 17:30:00,511,"Forest St, San Francisco, CA 94016",Forest St,San Francisco,CA 94016
11685,259357,USB-C Charging Cable,1,11.95,2019-09-30 00:18:00,250,"Meadow St, San Francisco, CA 94016",Meadow St,San Francisco,CA 94016

In [290]:
Data.drop('Address',axis=1,inplace=True)

C:\Users\MAHMOUD\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [291]:
Data

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Street Number,Street Name,City,State
0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,917,1st St,Dallas,TX 75001
2,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,682,Chestnut St,Boston,MA 02215
3,176560,Google Phone,1,600,2019-04-12 14:38:00,669,Spruce St,Los Angeles,CA 90001
4,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,669,Spruce St,Los Angeles,CA 90001
5,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,333,8th St,Los Angeles,CA 90001
...,...,...,...,...,...,...,...,...,...
11681,259353,AAA Batteries (4-pack),3,2.99,2019-09-17 20:56:00,840,Highland St,Los Angeles,CA 90001
11682,259354,iPhone,1,700,2019-09-01 16:00:00,216,Dogwood St,San Francisco,CA 94016
11683,259355,iPhone,1,700,2019-09-23 07:39:00,220,12th St,San Francisco,CA 94016
11684,259356,34in Ultrawide Monitor,1,379.99,2019-09-19 17:30:00,511,Forest St,San Francisco,CA 94016
11685,259357,USB-C Charging Cable,1,11.95,2019-09-30 00:18:00,250,Meadow St,San Francisco,CA 94016

In [292]:
State = Data['State'].str.split(' ', expand=True)
Data.drop('State',axis=1,inplace=True)

C:\Users\MAHMOUD\anaconda3\lib\site-packages\pandas\core\frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [293]:
Data['State'] = State[1]
Data['Postal code'] = State[2]
Data

C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/3961158295.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['State'] = State[1]
C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/3961158295.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Postal code'] = State[2]

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Street Number,Street Name,City,State,Postal code
0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,917,1st St,Dallas,TX,75001
2,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,682,Chestnut St,Boston,MA,02215
3,176560,Google Phone,1,600,2019-04-12 14:38:00,669,Spruce St,Los Angeles,CA,90001
4,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,669,Spruce St,Los Angeles,CA,90001
5,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,333,8th St,Los Angeles,CA,90001
...,...,...,...,...,...,...,...,...,...,...
11681,259353,AAA Batteries (4-pack),3,2.99,2019-09-17 20:56:00,840,Highland St,Los Angeles,CA,90001
11682,259354,iPhone,1,700,2019-09-01 16:00:00,216,Dogwood St,San Francisco,CA,94016
11683,259355,iPhone,1,700,2019-09-23 07:39:00,220,12th St,San Francisco,CA,94016
11684,259356,34in Ultrawide Monitor,1,379.99,2019-09-19 17:30:00,511,Forest St,San Francisco,CA,94016
11685,259357,USB-C Charging Cable,1,11.95,2019-09-30 00:18:00,250,Meadow St,San Francisco,CA,94016

In [294]:
Data['Quantity Ordered'] = Data['Quantity Ordered'].str.replace('[^\d.]', '', regex=True)
Data['Quantity Ordered'] = pd.to_numeric(Data['Quantity Ordered'], errors='coerce')
Data = Data.dropna(subset=['Quantity Ordered'])
Data['Price Each'] = Data['Price Each'].str.replace(' ', '', regex=True).astype(float)
Data.info()

C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/677488340.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Quantity Ordered'] = Data['Quantity Ordered'].str.replace('[^\d.]', '', regex=True)
C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/677488340.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Quantity Ordered'] = pd.to_numeric(Data['Quantity Ordered'], errors='coerce')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 185950 entries, 0 to 11685
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          185950 non-null  object
 1   Product           185950 non-null  object
 2   Quantity Ordered  185950 non-null  float64
 3   Price Each        185950 non-null  float64
 4   Order Date        185950 non-null  datetime64[ns]
 5   Street Number     185950 non-null  object
 6   Street Name       185950 non-null  object
 7   City              185950 non-null  object
 8   State             185950 non-null  object
 9   Postal code       185950 non-null  object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 15.6+ MB

C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/677488340.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Price Each'] = Data['Price Each'].str.replace(' ', '', regex=True).astype(float)

In [295]:
Data['Total Price'] = Data['Quantity Ordered'] * Data['Price Each']
Data

C:\Users\MAHMOUD\AppData\Local\Temp/ipykernel_29676/1789763065.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Data['Total Price'] = Data['Quantity Ordered'] * Data['Price Each']

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Street Number,Street Name,City,State,Postal code,Total Price
0,176558,USB-C Charging Cable,2.0,11.95,2019-04-19 08:46:00,917,1st St,Dallas,TX,75001,23.90
2,176559,Bose SoundSport Headphones,1.0,99.99,2019-04-07 22:30:00,682,Chestnut St,Boston,MA,02215,99.99
3,176560,Google Phone,1.0,600.00,2019-04-12 14:38:00,669,Spruce St,Los Angeles,CA,90001,600.00
4,176560,Wired Headphones,1.0,11.99,2019-04-12 14:38:00,669,Spruce St,Los Angeles,CA,90001,11.99
5,176561,Wired Headphones,1.0,11.99,2019-04-30 09:27:00,333,8th St,Los Angeles,CA,90001,11.99
...,...,...,...,...,...,...,...,...,...,...,...
11681,259353,AAA Batteries (4-pack),3.0,2.99,2019-09-17 20:56:00,840,Highland St,Los Angeles,CA,90001,8.97
11682,259354,iPhone,1.0,700.00,2019-09-01 16:00:00,216,Dogwood St,San Francisco,CA,94016,700.00
11683,259355,iPhone,1.0,700.00,2019-09-23 07:39:00,220,12th St,San Francisco,CA,94016,700.00
11684,259356,34in Ultrawide Monitor,1.0,379.99,2019-09-19 17:30:00,511,Forest St,San Francisco,CA,94016,379.99
11685,259357,USB-C Charging Cable,1.0,11.95,2019-09-30 00:18:00,250,Meadow St,San Francisco,CA,94016,11.95

Load

In [296]:
Data.to_csv('FullData.csv')